export const enum RouterName {
  Home = "/home",
  Info = "/info",
  Song = "/song",
  Singer = "/singer",
  SongList = "/songList",
  SwiperList = "/swiperList",
  ListSong = "/listSong",
  ListSwiper = "/listSwiper",
  Comment = "/Comment",
  Consumer = "/consumer",
  Collect = "/collect",
  Error = "/404",
  SignIn = "/",
  SignOut = "0",
}
